Feature/8
MEOStudio/vuonhoasu.org pull request #12
Opened 2022-09-16 04:46 UTC by YumeAyasaki

In this PR, I have:
- Add sass to the project...
- Create global styling, including variables, mixins (although there's nothing there), and some stylings for headings and text...
- Make a Test page to demo some of the changes...

Note: I think we should unify (?) more things, maybe size for phones and tablets (there're many phone sizes, I just go with the 390px width on Figma) and maybe make a mixin for that. And maybe some other mixins if other members want to use...

2022-09-18 00:09 UTC, TienDucHo reviewed
Please check the comment. The purpose of global stylesheet is not styling individual HTML elements but to make mixins and classes that can be imported and used everywhere, and also, reduce the amount the code needed to achieve the styling

2022-09-18 00:09 UTC, TienDucHo commented on styles/globals.scss
> +h1 { // Lora 32px bold
Change these styling into mixins or class. This will reduce the amount of repeated code.

2022-09-18 00:11 UTC, TienDucHo requested changes

2022-09-18 00:11 UTC, TienDucHo commented on styles/globals.scss
> +h1 { // Lora 32px bold
Add another comment here to request changes.

2022-09-19 17:34 UTC, YumeAyasaki commented
Update PR:
- Change global styling to class...
- Add a mixin for Lora font...
- Edit the Test page according to the new global styling...?

Note: I want to make a mixin for phone media query, do we use max-width or min-width for phone size...?

2022-09-20 06:48 UTC, TienDucHo requested changes

2022-09-20 06:48 UTC, TienDucHo commented on styles/globals.scss
> +.sub-header-2 { // Lora 24px bold
Please rename classes using camelUpperCase (eg. subHeader, subHeader2, ...)

2022-09-20 11:19 UTC, YumeAyasaki commented
Update PR:
- Change name class...

2022-09-21 13:00 UTC, TienDucHo requested changes

2022-09-21 13:00 UTC, TienDucHo commented on yarn.lock
> -# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Solve the conflict with develop branch

2022-09-21 13:04 UTC, TienDucHo commented
LGTM

2022-09-21 13:04 UTC, merged