Feature/7
MEOStudio/vuonhoasu.org pull request #13
Opened 2022-09-16 04:55 UTC by YumeAyasaki

In this PR, I have:

- Checkout from the feature/8 branch...
- Make a footer component...
- Add icons to the public folder...
- Include said component to the _app.js file, thus making it a theme component...

Note: About the icon, should we use a library for that, or use the font in Figma or just export and include it inside the public folder...?

![localhost_3000_Test - Cá nhân 1 - Microsoft​ Edge 9_16_2022 11_54_37 AM](https://user-images.githubusercontent.com/43096050/190559604-eea9f6f5-872c-46b3-a953-540cb5baed43.png)

2022-09-18 00:15 UTC, TienDucHo requested changes
Please check the comments.

2022-09-18 00:15 UTC, TienDucHo commented on components/theme/footer.jsx
> +        Vườn hoa sứ
Change this to "Vườn Hoa Sứ"

2022-09-18 00:15 UTC, TienDucHo commented on components/theme/footer.jsx
> +        <div className={styles.icon}><Image src='/icons/facebook.svg' alt='facebook' layout='fill' objectFit='contain'/></div>
Please use the library "[react-icons](https://react-icons.github.io/react-icons/)" for this

2022-09-18 00:15 UTC, TienDucHo commented on components/theme/footer.module.scss
> +    .title {
Apply global styling to these element after changing the styling into classes or mixins

2022-09-19 17:42 UTC, YumeAyasaki commented
Update PR:
- Rename to Vuon Hoa Su...
- Apply react-icons...
- Edit minor things to match the new global styling...

Note: As you can see, the old module sass file doesn't match well with the new global styling. Any idea for that...?

2022-09-20 06:50 UTC, TienDucHo requested changes

2022-09-20 06:50 UTC, TienDucHo commented on components/theme/footer.module.scss
>      }
Please capitalize the component's name (eg Footer, not footer)

2022-09-20 11:21 UTC, YumeAyasaki commented
Update PR:
- Update some name classes...
- Rename footer to Footer...

Note: Do you have any idea regarding the name change commit of VS Code...?

2022-09-21 13:05 UTC, TienDucHo commented
LGTM

2022-09-21 13:05 UTC, merged