Feature/6
MEOStudio/vuonhoasu.org pull request #14
Opened 2022-09-16 05:05 UTC by YumeAyasaki

In this PR, I have:

- Checkout from the feature/8 branch...
- Make a footer component...
- Add icons to the public folder...
- Include said component to the _app.js file, thus making it a theme component...
- And IDK if this's needed or not, I make the dropdown menu (Navbar) can be turned off (?) by clicking outside of said dropdown...

Note: The same note as the feature/7, about the icons. And one more, do we need to make this component, like, universal? There's some web that has the Navbar highlight the section they're currently in, but considering our current design, I don't know if we should do that or not...
And I have yet done the linking things...
![localhost_3000_Test - Cá nhân 1 - Microsoft​ Edge 9_16_2022 12_04_28 PM](https://user-images.githubusercontent.com/43096050/190560597-f338efe6-79f8-42da-86c9-ca3c08fb21ba.png)
![localhost_3000_Test - Cá nhân 1 - Microsoft​ Edge 9_16_2022 12_04_10 PM](https://user-images.githubusercontent.com/43096050/190560605-ef14329e-ae7d-452f-9d0a-827c9f12a7da.png)
![localhost_3000_Test - Cá nhân 1 - Microsoft​ Edge 9_16_2022 12_04_19 PM](https://user-images.githubusercontent.com/43096050/190560609-eb3e0200-d3d0-487b-98f5-ee7bb61be3de.png)

2022-09-18 00:27 UTC, TienDucHo requested changes

2022-09-18 00:27 UTC, TienDucHo commented on components/theme/Navbar.jsx
> +            <h3 className={styles.title}>Vườn hoa sứ</h3>
Change to "Vườn Hoa Sứ"

2022-09-18 00:27 UTC, TienDucHo commented on components/theme/Navbar.jsx
> +        <h3 className={styles.left}>
Change to "Vườn Hoa Sứ"

2022-09-18 00:27 UTC, TienDucHo commented on components/theme/Navbar.jsx
> +              <Image src='/icons/Bars.svg' alt='button' layout='fill' objectFit='contain'/>
Please use [react-icons](https://react-icons.github.io/react-icons/)

2022-09-18 00:27 UTC, TienDucHo commented on components/theme/Navbar.module.scss
> +.header {
Please make use of mixins and classes

2022-09-19 17:45 UTC, YumeAyasaki commented
Update PR:
- Change to Vuon Hoa Su...
- Apply react-icons...
- Edit minor things to match the new global styling...

Note: The same question from the feature/6 + should I update PR with a new comment like this, or reply to your changes requested comment...?

2022-09-20 06:50 UTC, TienDucHo commented
> 

Either is fine

2022-09-20 06:52 UTC, TienDucHo requested changes

2022-09-20 06:52 UTC, TienDucHo commented on components/theme/Navbar.jsx
> +          <div className='sub-header-2'>Vườn Hoa Sứ</div>
Please rename class after you rename global styling

2022-09-20 11:21 UTC, YumeAyasaki commented
Update PR:
- Update name class...

2022-09-21 13:07 UTC, PaulHo0501 commented
Please solve all the conflicts

2022-09-21 13:21 UTC, PaulHo0501 commented
LGTM

2022-09-21 13:21 UTC, merged